name: Node.js CI

on:
  schedule:
    - cron: '0 */6 * * *'  # Atur sesuai kebutuhan Anda
  workflow_dispatch:  # Memungkinkan pemicu manual dari tab Actions di GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: sudo apt-get update && sudo apt-get install -y ffmpeg imagemagick
      - run: npm install
      - run: npm start
      - name: Check for changes
        run: |
          cd /home/runner/work/delta-neww/delta-neww
          git diff --exit-code  # Memeriksa apakah ada perubahan
        continue-on-error: true  # Jika tidak ada perubahan, langkah ini tidak gagal
      - name: Upload database files to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.ZALL_GITHUB_TOKEN }}  # Menggunakan token dari secrets
        run: |
          cd /home/runner/work/delta-neww/delta-neww
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add database
          git diff --cached --quiet || git commit -m "Update database files"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:master
